// Generated by PSWayforge (Sync-WayforgeHarness -Harness pi). Do not edit.
// Blocks a tool call by delegating to the shared Wayforge gate shim.
import { spawnSync } from "node:child_process";
import { join } from "node:path";

export default function (pi: any) {
  pi.on("tool_call", async (event: any, ctx: any) => {
    const cwd = ctx && ctx.cwd ? ctx.cwd : process.cwd();
    const script = join(cwd, ".workflow", "hooks", "gate.ps1");
    const payload = JSON.stringify({ tool_name: event.toolName, tool_input: event.input });
    const r = spawnSync("pwsh", ["-NoProfile", "-File", script, "-Stage", "pre-tool", "-AsHook", "pi"], { input: payload, encoding: "utf8" });
    if (r.status !== 0) {
      const reason = ((r.stdout || "") + (r.stderr || "")).trim();
      return { block: true, reason: reason || `Wayforge gate blocked this tool (exit ${r.status}).` };
    }
  });
}
