// Generated by PSWayforge (Sync-WayforgeHarness -Harness opencode). Do not edit.
// Blocks a tool call by delegating to the shared Wayforge gate shim.
import { spawnSync } from "node:child_process";

export const WayforgeGate = async ({ directory }) => {
  const root = directory ? String(directory).replace(/\\/g, "/").replace(/\/$/, "") + "/" : "";
  const script = root + ".workflow/hooks/gate.ps1";
  return {
    "tool.execute.before": async (input, output) => {
      const payload = JSON.stringify({ tool_name: input.tool, tool_input: output.args });
      const r = spawnSync("pwsh", ["-NoProfile", "-File", script, "-Stage", "pre-tool", "-AsHook", "opencode"], { input: payload, encoding: "utf8" });
      if (r.status !== 0) {
        const reason = ((r.stdout || "") + (r.stderr || "")).trim();
        throw new Error(reason || `Wayforge gate blocked this tool (exit ${r.status}).`);
      }
    },
  };
};
